#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ICONS_DIR = './src/lib/components/Icons';
const INDEX_FILE = path.join(ICONS_DIR, 'index.ts');

function scanIconFiles() {
	console.log('🔍 Scanning Icons directory...');

	const files = fs.readdirSync(ICONS_DIR);
	const iconFiles = files.filter((file) => file.endsWith('.ts') && file !== 'index.ts');

	console.log(`📊 Found ${iconFiles.length} icon files`);

	const icons = [];

	for (const file of iconFiles) {
		const filePath = path.join(ICONS_DIR, file);
		const content = fs.readFileSync(filePath, 'utf8');

		// Extract icon name from filename (remove .ts extension)
		const iconName = path.basename(file, '.ts');

		// Extract all exported icon variants from the file
		const exportMatches = content.match(/export const (\w+) = icon\(/g);

		if (exportMatches) {
			const variants = exportMatches.map((match) => {
				const variant = match.match(/export const (\w+) = icon\(/)[1];
				return variant;
			});

			icons.push({
				name: iconName,
				file: file,
				variants: variants
			});
		}
	}

	return icons.sort((a, b) => a.name.localeCompare(b.name));
}

function generateIndexFile(icons) {
	console.log('📝 Generating index.ts file...');

	let content = `// Auto-generated icon barrel file
// Do not edit this file directly - run 'node generate-icons.js' to regenerate

`;

	// Add imports for each icon file
	for (const icon of icons) {
		content += `export {\n`;
		for (const variant of icon.variants) {
			content += `  ${variant},\n`;
		}
		content += `} from './${icon.name}.js';\n`;
	}

	fs.writeFileSync(INDEX_FILE, content);
	console.log(`✅ Generated ${INDEX_FILE}`);
}

function generateAgentDocumentation(icons) {
	console.log('📖 Generating agent documentation...');

	const agentDoc = `
export const agent = \`
# Icon System

This component library includes ${icons.length} icons from Phosphor Icons, each available in multiple variants. All icons are SVG-based and fully customizable.

## Available Variants

Each icon typically includes these variants:
- **Icon** (regular) - Standard weight
- **IconBold** - Bold weight  
- **IconDuotone** - Two-tone style
- **IconFill** - Filled style
- **IconLight** - Light weight
- **IconThin** - Thin weight

## Usage

### Import Individual Icons
\\\`\\\`\\\`typescript
import { homeIcon, homeIconBold, homeIconFill } from '$lib/components/Icons';
\\\`\\\`\\\`

### Barrel Import (Not Recommended)
\\\`\\\`\\\`typescript
import * as Icons from '$lib/components/Icons';

// Use specific icons
const HomeIcon = Icons.homeIcon;
\\\`\\\`\\\`

## Icon Component Usage

Icons are functions that return SVG snippets. Use them in Svelte components:

\\\`\\\`\\\`svelte
<script>
  import { homeIcon, settingsIconBold } from '$lib/components/Icons';
</script>

<!-- Direct SVG rendering -->
{@render homeIcon()}

<!-- With custom props -->
{@render settingsIconBold({ size: 32, color: '#3b82f6' })}

<!-- With CSS classes -->
<div class="w-6 h-6 text-blue-500">
  {@render settingsIconBold()}
</div>
\\\`\\\`\\\`

## Icon Props

Icons accept the following props:
- **size**: number (default: 24) - Size in pixels
- **color**: string (default: 'currentColor') - Icon color  
- **mirrored**: boolean (default: false) - Flip the icon horizontally
- Any standard SVG attributes (class, style, etc.)

\\\`\\\`\\\`svelte
<!-- Examples -->
{@render homeIcon()}                                    <!-- Default -->
{@render homeIcon({ size: 48 })}                        <!-- Large -->
{@render homeIcon({ color: '#ef4444' })}                <!-- Custom color -->
{@render arrowRightIcon({ mirrored: true })}            <!-- Mirrored -->
{@render settingsIcon({ size: 32, class: 'animate-spin' })} <!-- With class -->
\\\`\\\`\\\`

## Available Icons

This library includes ${icons.length} icons. Each icon has 6 variants: regular, bold, duotone, fill, light, and thin.

### Icon List

${icons.map((icon) => `\`${icon.name}\``).join(', ')}

## Icon Categories

The icons cover these main categories:
- **Interface**: Arrows, navigation, controls, UI elements
- **Communication**: Chat, mail, phone, social media
- **Media**: Play, pause, music, video controls  
- **Files**: Documents, folders, file types
- **Business**: Office, finance, charts, buildings
- **Technology**: Devices, code, networks, software
- **Nature**: Weather, plants, animals
- **Transportation**: Cars, planes, transit
- **Shopping**: Cart, payment, commerce
- **User**: Profile, account, people
- **System**: Settings, tools, configuration

## Customization

Icons inherit the current text color and can be styled with CSS:

\\\`\\\`\\\`svelte
<style>
  .icon {
    width: 24px;
    height: 24px;
    color: #3b82f6;
  }
  
  .icon:hover {
    color: #1d4ed8;
  }
</style>

<div class="icon">
  {@render homeIcon()}
</div>
\\\`\\\`\\\`

## Best Practices

1. **Consistent Sizing**: Use consistent icon sizes within the same interface
2. **Semantic Usage**: Choose icons that clearly represent their function
3. **Accessibility**: Provide alt text or aria-labels for important icons
4. **Performance**: Import only the icons you need to reduce bundle size
5. **Variants**: Use appropriate variants for visual hierarchy and emphasis

## Notes

- All icons are generated from Phosphor Icons
- Icons are tree-shakeable when imported individually
- Icons return Svelte snippets for optimal performance
- Icons automatically inherit text color from parent elements
- All icon files are TypeScript compatible
- Use {@render iconName()} syntax in Svelte 5
\`;
`;

	const agentFile = path.join(ICONS_DIR, 'agent.ts');
	fs.writeFileSync(agentFile, agentDoc);
	console.log(`✅ Generated ${agentFile}`);
}

function updatePackageJson() {
	console.log('📦 Updating package.json exports...');

	const packagePath = './package.json';
	const packageContent = fs.readFileSync(packagePath, 'utf8');
	const packageJson = JSON.parse(packageContent);

	// Initialize exports if it doesn't exist
	if (!packageJson.exports) {
		packageJson.exports = {};
	}

	// Add icons export
	packageJson.exports['./icons'] = {
		types: './dist/components/Icons/index.d.ts',
		default: './dist/components/Icons/index.js'
	};

	// Ensure the main export includes icons
	if (!packageJson.exports['./icons/*']) {
		packageJson.exports['./icons/*'] = {
			types: './dist/components/Icons/*.d.ts',
			default: './dist/components/Icons/*.js'
		};
	}

	fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
	console.log('✅ Updated package.json exports');
}

function main() {
	console.log('🚀 Starting icon generation process...');

	try {
		const icons = scanIconFiles();
		generateIndexFile(icons);
		generateAgentDocumentation(icons);
		updatePackageJson();

		console.log('🎉 Icon generation completed successfully!');
		console.log(`📊 Generated exports for ${icons.length} icons`);
		console.log('💡 Run this script whenever you add new icons to update the exports');
	} catch (error) {
		console.error('❌ Error during icon generation:', error);
		process.exit(1);
	}
}

// Run the script
if (import.meta.url === `file://${process.argv[1]}`) {
	main();
}

export { scanIconFiles, generateIndexFile, generateAgentDocumentation, updatePackageJson };
